  [backends]
    [backends.backend-xymon]
      [backends.backend-xymon.servers.server-xymon]
         url = "http://sd-XXXXX.dedibox.fr/"

  [frontends]
    [frontends.frontend-Host-xymon-example-com-0]
      backend = "backend-xymon"
      passHostHeader = true
      entrypoints = ["http", "https"]
        [frontends.frontend-Host-xymon-example-com-0.routes.route-frontend-Host-xymon-example-com-0]
        rule = "Host:xymon.example.com"
