  [backends]

    [backends.backend-xymon]
      [backends.backend-xymon.servers.server-xymon]
         url = "http://sd-xxx.dedibox.fr/"

  [frontends]

    [frontends.frontend-xymon]
      entrypoints = ["http", "https"]
      backend = "backend-xymon"
      passHostHeader = true
      whitelistSourceRange = ["127.0.0.1/32", "IP1/32", "IP2/32", "...", "IPN/32"]

    [frontends.frontend-xymon.routes]
      [frontends.frontend-xymon.routes.route-xymon]
        rule = "Host:xymon.example.com"
