version: '3'
services:
  ts3_db:
    container_name: ts3_db_1
    image: mariadb:10.4.12-bionic
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <mysql_root_password>
      MYSQL_DATABASE: teamspeak
    volumes:
      - $PWD/ts3/mariadb/data:/var/lib/mysql

  ts3_core:
    container_name: ts3_core_1
    image: teamspeak:3.11.0
    restart: always
    links:
      - ts3_db
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: ts3_db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: <mysql_root_password>
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
      TS3SERVER_IP_WHITELIST: /whitelist.txt
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - $PWD/ts3/core/whitelist.txt:/whitelist.txt
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - '2008:2008'      # accounting port
      - '2010:2010/udp'  # weblist port
      - '9987:9987/udp'  # default port (voice)
      - '30033:30033'    # filetransfer port
      - '41144:41144'    # tsdns port

  # ts3_web:
  #   container_name: ts3_web_1
  #   image: ts3web
  #   restart: always
  #   environment:
  #     ALIAS: 'My Testserver'
  #     HOST: 'ts3'
  #     PORT: '10011'
  #     LANG: 'en'
  #   ports:
  #     - '8080:80'        # webinterface port (host:container)
