# traefik.toml
################################################################
# Global configuration
################################################################

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.dashboard]
  address = ":8090"

  [entryPoints.api]
  address = ":8080"
  [entryPoints.api.auth]
    [entryPoints.api.auth.basic]
      users = ["return htpasswd command"] # Command: htpasswd -n admin
  [api.statistics]
    recentErrors = 10

  [entryPoints.ping]
  address = ":8081"

  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[ping]
entryPoint = "ping"

[api]
entryPoint = "api"
dashboard = true

# [web]
# address = ":8080"
# [web.auth.basic]
#   users = ["return htpasswd command"] # Command: htpasswd -n admin

# Enable ACME (Let's Encrypt): automatic SSL.
# https://docs.traefik.io/configuration/acme/
[acme]
email = "email@example.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true # false
onHostRule = false # For generete unique certificat for domain

[acme.httpChallenge]
  entryPoint = "http"

  [acme.dnsChallenge]
  # https://api.ovh.com/createToken/
  # https://eu.api.ovh.com/console/
  # https://github.com/wheniwork/harpoon/blob/master/docker-compose.yml
  # https://www.bardina.net/traefik-gitlab-docker/
  # https://www.g-rom.info/2017/06/creer-des-certificats-letsencrypt-avec-les-dns-de-ovh/
  provider = "ovh"
  delayBeforeCheck = 0

[[acme.domains]]
  main = "example.com"
  sans = ["subdomain1.example.com",
       "subdomain2.example.com",
       ...,
       "subdomainN.example.com",
       ]

# Accepted values, in order of severity: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# Messages at and above the selected level will be logged.
[traefikLog]
  filePath = "/etc/traefik/logs/traefik.log"
  logLevel = "DEBUG"
  format = "common" # "json" # or "common"

[accessLog]
  filePath = "/etc/traefik/logs/access.log"
  logLevel = "INFO"
  format = "common" # "json" # or "common"

[file]
  directory = "/etc/traefik/toml"
  watch = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedbydefault = true

# https://docs.traefik.io/configuration/metrics/
# [metrics]
